<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends BaseArticleRepository
{
    public function findByTag($id)
    {
        $qb = $this->createQueryBuilder('data');

        $qb
            ->select('data')
            ->leftJoin('data.tags', 'tags')
            ->where('tags.id = :id')
            ->setParameter('id', $id);
        return $qb->getQuery();
    }
}
