<?php

namespace AppBundle\Repository;

/**
 * AuthorArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorArticleRepository extends BaseArticleRepository
{
}
