<?php

namespace AppBundle\Repository;

/**
 * BaseArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseArticleRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param array $where
     * @param null $orderBy
     * @return \Doctrine\ORM\Query
     */
    public function pagerfanta(array $where = [], $orderBy = null)
    {
        $sql = $this->createQueryBuilder('data');
        $sql->select('data');
        if (count($where)) {
            foreach ($where as $key => $value) {
                $sql->andWhere('data.' . $key . ' = :' . $key);
                $sql->setParameter($key, $value);
            }
        }
        if ($orderBy) {
            $orderBy = explode(':', $orderBy);
            $by = $orderBy[1] ?? 'asc';
            $orderBy = $orderBy[0];
            $sql
                ->orderBy('data.' . $orderBy, $by);
        }
        return $sql->getQuery();
    }
}
